version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/projects/ngx-google-analytics"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
